# Axon API Gateway Configuration Example
# This configuration shows how to set up the axon gateway with various routing strategies

listen_addr: "0.0.0.0:8080"

# Health check configuration
health_check:
  enabled: true
  path: "/health"
  interval_secs: 30
  timeout_secs: 5

# Protocol support configuration
protocols:
  http2_enabled: true
  websocket_enabled: true
  http3_enabled: false
  http2_max_frame_size: 65536
  http2_max_concurrent_streams: 100

# TLS configuration (optional)
# tls:
#   cert_path: "/path/to/cert.pem"
#   key_path: "/path/to/key.pem"
#   protocols:
#     - "TLSv1.2"
#     - "TLSv1.3"

# Route configurations
routes:
  # API routes with load balancing
  "/api/v1/":
    type: "load_balance"
    targets:
      - "http://backend1:3000"
      - "http://backend2:3000"
      - "http://backend3:3000"
    strategy: "round_robin"
    rate_limit:
      requests_per_minute: 100
      burst_size: 20
    request_headers:
      add:
        "X-Gateway": "axon"
        "X-Forwarded-Proto": "https"
      remove:
        - "Server"
    response_headers:
      add:
        "X-Response-Time": "auto"
        "Cache-Control": "no-cache"

  # Single backend proxy
  "/auth/":
    type: "proxy"
    target: "http://auth-service:4000"
    path_rewrite: "/auth/(.*)" # Optional: rewrite path
    rate_limit:
      requests_per_minute: 50
      burst_size: 10

  # Static file serving
  "/static/":
    type: "static"
    root: "/var/www/static"
    rate_limit:
      requests_per_minute: 200
      burst_size: 50

  # Redirect example
  "/old-api/":
    type: "redirect"
    target: "/api/v1/"
    status_code: 301

  # WebSocket proxy
  "/ws/":
    type: "proxy"
    target: "ws://websocket-service:5000"

# Backend-specific health check paths
backend_health_paths:
  "http://backend1:3000": "/health"
  "http://backend2:3000": "/health"
  "http://backend3:3000": "/health"
  "http://auth-service:4000": "/health/check"
