# Health check scenario
listen_addr = "127.0.0.1:8084"

[routes."/api/"]
type = "load_balance"
strategy = "round_robin"

targets = [
  "http://127.0.0.1:9201",
  "http://127.0.0.1:9202",
]

[health_check]
enabled = true
path = "/health"
interval_secs = 1
timeout_secs = 1
unhealthy_threshold = 1
healthy_threshold = 1

[backend_health_paths]
"http://127.0.0.1:9201" = "/health"
"http://127.0.0.1:9202" = "/health"
