# HTTP/3 proxy example configuration
#
# This example enables the experimental HTTP/3 (QUIC) listener alongside the
# existing HTTP/1.1 listener on the same address. A single proxy route /api
# forwards to a backend started by the accompanying script.

listen_addr = "127.0.0.1:8095"

[protocols]
http2_enabled = false
websocket_enabled = false
http3_enabled = true

[tls]
# The example script generates these at runtime via openssl.
cert_path = "cert.pem"
key_path = "key.pem"

[health_check]
enabled = false

[routes."/api"]
type = "proxy"
target = "http://127.0.0.1:9095"
