# Single backend proxy with explicit root rewrite to backend
listen_addr = "127.0.0.1:8081"

[health_check]
enabled = false

[routes."/api"]
type = "proxy"
# Explicitly rewrite /api -> / (backend root) to ensure 200 from python http.server
path_rewrite = "/"
target = "http://127.0.0.1:9001"
